"use client";

import Link from "next/link";
import { ArrowLeft, Shield } from "lucide-react";

export default function PrivacyPage() {
  return (
    <div className="min-h-dvh bg-[#050510] text-white">
      {/* ─── Background Glow ─── */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-0 right-0 w-80 h-80 rounded-full bg-cyan-600/8 blur-[120px]" />
        <div className="absolute bottom-0 left-0 w-96 h-96 rounded-full bg-purple-600/10 blur-[140px]" />
      </div>

      <div className="relative z-10 mx-auto max-w-2xl px-6 py-12">
        {/* ─── Header ─── */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-white/50 hover:text-white/80 transition-colors mb-8 group"
        >
          <ArrowLeft className="h-4 w-4 group-hover:-translate-x-1 transition-transform" />
          Back to App
        </Link>

        <div className="flex items-center gap-3 mb-2">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{
              background: "linear-gradient(135deg, rgba(6,182,212,0.2), rgba(139,92,246,0.2))",
            }}
          >
            <Shield className="h-5 w-5 text-cyan-400" />
          </div>
          <h1 className="text-2xl font-bold tracking-tight">Privacy Policy</h1>
        </div>
        <p className="text-sm text-white/40 mb-10">Last updated: April 22, 2026</p>

        {/* ─── Content ─── */}
        <div className="space-y-8 text-[15px] leading-relaxed text-white/70">
          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">1. Introduction</h2>
            <p>
              Vibe & Aura ("we," "us," or "the App") respects your privacy. This Privacy Policy explains what information we collect, how we use it, and the choices you have. By using the App, you consent to the practices described below.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">2. Information We Collect</h2>
            
            <h3 className="text-[15px] font-medium text-white/80 mt-4 mb-2">2.1 Information You Provide</h3>
            <ul className="space-y-2 list-none">
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Zodiac Sign & Age:</strong> Used solely to personalize your personality analysis.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Relationship Status:</strong> Optional input used to tailor AI-generated content.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Photos:</strong> If you choose to upload a photo for analysis, the image is processed temporarily for the AI analysis and is <strong>not stored permanently on our servers</strong>.</span>
              </li>
            </ul>

            <h3 className="text-[15px] font-medium text-white/80 mt-4 mb-2">2.2 Automatically Collected Data</h3>
            <ul className="space-y-2 list-none">
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Anonymous User ID:</strong> Generated by Firebase Authentication to identify your session. No personal information (name, email, phone) is required or collected.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Device FCM Token:</strong> If you opt in to push notifications, your device token is stored to deliver notifications. It is not shared with third parties.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span><strong className="text-white/90">Usage Analytics:</strong> We may collect anonymized usage statistics (e.g., feature popularity, crash reports) to improve the App.</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">3. Photos & Images</h2>
            <div
              className="p-4 rounded-2xl border mb-4"
              style={{
                background: "rgba(6,182,212,0.08)",
                borderColor: "rgba(6,182,212,0.2)",
              }}
            >
              <p className="text-cyan-300 font-medium text-sm">
                🔒 We do <strong>NOT</strong> store, sell, share, or use your photos for any purpose beyond the immediate AI analysis you request.
              </p>
            </div>
            <p>
              Photos uploaded for personality analysis are processed in real-time by our AI models and are discarded immediately after the analysis is generated. We do not retain copies of your images on any server. We never sell or share your images with third parties, advertisers, or data brokers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">4. How We Use Your Data</h2>
            <ul className="space-y-2 list-none">
              <li className="flex gap-2">
                <span className="text-purple-400 mt-1">→</span>
                <span>To generate personalized personality analyses and zodiac-based entertainment content.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-purple-400 mt-1">→</span>
                <span>To manage your token balance and subscription status.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-purple-400 mt-1">→</span>
                <span>To send push notifications (only with your explicit consent).</span>
              </li>
              <li className="flex gap-2">
                <span className="text-purple-400 mt-1">→</span>
                <span>To improve the App's features, performance, and stability.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-purple-400 mt-1">→</span>
                <span>To process payments via Polar or app store billing systems.</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">5. Third-Party Services</h2>
            <p className="mb-3">We integrate the following trusted third-party services:</p>
            <div className="grid gap-3">
              {[
                { name: "Firebase (Google)", desc: "Authentication, database, and push notifications" },
                { name: "Google Gemini AI", desc: "AI-powered entertainment and personality analysis" },
                { name: "Polar", desc: "Secure payment processing for web purchases" },
                { name: "RevenueCat", desc: "In-app purchase management for mobile platforms" },
              ].map((service) => (
                <div
                  key={service.name}
                  className="flex items-start gap-3 p-3 rounded-xl border"
                  style={{
                    background: "rgba(255,255,255,0.03)",
                    borderColor: "rgba(255,255,255,0.08)",
                  }}
                >
                  <div className="w-2 h-2 rounded-full bg-purple-400 mt-1.5 shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-white/80">{service.name}</p>
                    <p className="text-xs text-white/40">{service.desc}</p>
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-3 text-sm">
              Each service has its own privacy policy. We encourage you to review them independently.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">6. Data Retention</h2>
            <ul className="space-y-2 list-none">
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span>Analysis history is stored in your Firestore user document for your reference.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span>Photos are <strong>never</strong> permanently stored.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">•</span>
                <span>You may request deletion of all your data by contacting us.</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">7. Children's Privacy</h2>
            <p>
              Vibe & Aura is not intended for children under the age of 13 (or the minimum age required in your jurisdiction). We do not knowingly collect personal information from children. If we discover that a child has provided us with personal information, we will delete it promptly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">8. Your Rights</h2>
            <p className="mb-2">Depending on your jurisdiction, you may have the right to:</p>
            <ul className="space-y-1.5 list-none">
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">✓</span>
                <span>Access the personal data we hold about you.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">✓</span>
                <span>Request correction or deletion of your data.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">✓</span>
                <span>Withdraw consent for push notifications at any time.</span>
              </li>
              <li className="flex gap-2">
                <span className="text-cyan-400 mt-1">✓</span>
                <span>Lodge a complaint with a data protection authority.</span>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">9. Security</h2>
            <p>
              We use industry-standard security measures including encrypted communications (HTTPS/TLS), Firebase security rules, Polar's secure payment processing, and server-side authentication to protect your data. However, no system is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy periodically. We will notify you of significant changes through the App. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white/90 mb-3">11. Contact Us</h2>
            <p>
              For privacy-related inquiries, data deletion requests, or concerns, contact us at{" "}
              <a href="mailto:privacy@vibeandaura.app" className="text-cyan-400 hover:text-cyan-300 underline underline-offset-2 transition-colors">
                privacy@vibeandaura.app
              </a>
            </p>
          </section>
        </div>

        {/* ─── Footer ─── */}
        <div className="mt-16 pt-8 border-t border-white/10 text-center">
          <p className="text-xs text-white/30">
            © {new Date().getFullYear()} Vibe & Aura. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
